# Generated by Django 3.2 on 2022-01-22 21:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Pitch',
            fields=[
                ('pitch_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('pitch_type', models.CharField(choices=[('T', 'Tent'), ('V', 'Van'), ('C', 'Caravan'), ('M', 'Motorhome')], max_length=2)),
                ('availability', models.BooleanField(default=True)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('pitch_want', models.CharField(choices=[('T', 'Tent'), ('V', 'Van'), ('C', 'Caravan'), ('M', 'Motorhome')], max_length=2)),
                ('date_from', models.DateField(default=django.utils.timezone.now)),
                ('date_to', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('P', 'Pending'), ('C', 'Cancelled'), ('A', 'Approved')], max_length=2)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.customer')),
                ('pitch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.pitch')),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
